/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 planet.gltf
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { LinearEncoding } from 'three';

export default (props) => {
  const { nodes, materials } = useGLTF('/planet-core.gltf');
  console.log(nodes);
  return (
    <group {...props} scale={2} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry}>
        <meshStandardMaterial
          map={materials['Material.001'].map}
          normalMap={materials['Material.001'].normalMap}
          normalScale={materials['Material.001'].normalScale}
          normalMap-encoding={LinearEncoding}
        />
      </mesh>
      <mesh
        scale={1.015}
        geometry={nodes.Sphere001.geometry}
        material={materials['Material.002']}
      />
    </group>
  );
};

useGLTF.preload('/planet-core.gltf');
